"""Prompt templates for AI agents."""

from .financial_analysis import (
    FINANCIAL_MODEL_SYSTEM_PROMPT,
    STRUCTURE_ANALYSIS_PROMPT,
    METRIC_EXTRACTION_PROMPT,
    VALIDATION_PROMPT,
    INSIGHT_GENERATION_PROMPT
)

__all__ = [
    'FINANCIAL_MODEL_SYSTEM_PROMPT',
    'STRUCTURE_ANALYSIS_PROMPT',
    'METRIC_EXTRACTION_PROMPT',
    'VALIDATION_PROMPT',
    'INSIGHT_GENERATION_PROMPT'
]
